import { chromium } from 'playwright';
const b = await chromium.launch();
const ctx = await b.newContext({ viewport:{width:1440,height:900} });
let patched=0;
await ctx.route('**/icons.tsx*', async (r)=>{ patched++; const res=await r.fetch(); let x=await res.text();
  const before=x.length;
  for(const n of ['Instagram','Linkedin','Twitter','Youtube']) x=x.replace(new RegExp(`(,\\s*)${n}(?=[,\\s}])`),'');
  x=x.replace('var _jsxFileName','const Instagram=Circle,Linkedin=Circle,Twitter=Circle,Youtube=Circle;\nvar _jsxFileName');
  console.log('patched icons.tsx, len', before, '->', x.length, 'hasInstagramImport:', /,\s*Instagram\s*,/.test(x));
  await r.fulfill({body:x,headers:{...res.headers(),'content-type':'text/javascript'}});});
const p = await ctx.newPage();
p.on('pageerror',e=>console.log('PAGEERROR:', e.message.slice(0,160)));
p.on('console',m=>{if(m.type()==='error')console.log('CONSOLE:',m.text().slice(0,160));});
await p.goto('http://localhost:5174/services',{waitUntil:'networkidle'});
await p.waitForTimeout(2000);
console.log('routes hit:', patched, 'root kids:', await p.evaluate(()=>document.getElementById('root')?.children.length));
await b.close();
